name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - run: strace ./app
    - run: strace ./cntnr ./app
    - run: strace python3 app.py
    - run: strace ./cntnr python3 app.py